/**
 * Shared event filtering utilities for Slack events
 */

import type { GatewayConfig } from "../../cli/config";

/**
 * Check if a Slack event was generated by the bot itself
 * Used to filter out self-generated events to prevent loops
 */
export function isSelfGeneratedEvent(
  event: any,
  config: GatewayConfig
): boolean {
  const botUserId = config.slack.botUserId;
  const botId = config.slack.botId;

  const isSelf =
    (botId && event.bot_id && event.bot_id === botId) ||
    (botUserId && event.user === botUserId);

  return isSelf;
}
